import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const migrationPath = new URL("../supabase/migrations/20260814193000_create_feedback_reports.sql", import.meta.url);

test("creates the reports table with RLS and backend-only access", async () => {
  const migration = await readFile(migrationPath, "utf8");

  assert.match(migration, /create table if not exists public\.reports/i);
  assert.match(migration, /public_number bigint generated by default as identity/i);
  assert.match(migration, /unique\s*\(\s*public_number\s*\)/i);
  assert.match(migration, /enable row level security/i);
  assert.match(migration, /revoke all on table public\.reports from anon, authenticated/i);
  assert.doesNotMatch(migration, /create policy/i);
  assert.match(migration, /check \(status in \('Pending', 'Validating', 'In construction', 'Resolved', 'Discarded'\)\)/i);
  assert.match(migration, /check \(severity in \('Low', 'Medium', 'High'\)\)/i);
  assert.match(migration, /check \(type in \('Bug', 'Improvement'\)\)/i);
});

test("adds durable discard state, maintained timestamps, and immutable status audit events", async () => {
  const migration = await readFile(
    new URL("../supabase/migrations/20260814213000_add_creator_report_workflow.sql", import.meta.url),
    "utf8",
  );

  assert.match(migration, /add column if not exists discard_reason text/i);
  assert.match(migration, /create trigger maintain_reports_updated_at/i);
  assert.match(migration, /create table if not exists public\.report_status_events/i);
  assert.match(migration, /actor_id uuid not null/i);
  assert.match(migration, /report_id uuid not null references public\.reports\(id\)/i);
  assert.match(migration, /old_status text not null/i);
  assert.match(migration, /new_status text not null/i);
  assert.match(migration, /request_id uuid not null/i);
  assert.match(migration, /create trigger prevent_report_status_event_changes/i);
  assert.match(migration, /create or replace function public\.update_report_status/i);
  assert.match(migration, /for update/i);
  assert.match(migration, /insert into public\.report_status_events/i);
  assert.match(migration, /revoke all on function public\.update_report_status/i);
  assert.match(migration, /grant execute on function public\.update_report_status/i);
});

test("adds an atomic backend-only rate-limit bucket without raw subjects", async () => {
  const migration = await readFile(
    new URL("../supabase/migrations/20260814230000_add_durable_rate_limits.sql", import.meta.url),
    "utf8",
  );

  assert.match(migration, /create table if not exists public\.rate_limit_buckets/i);
  assert.match(migration, /bucket_hash text primary key/i);
  assert.doesNotMatch(migration, /bearer|jwt|email|ip_address|raw_subject/i);
  assert.match(migration, /enable row level security/i);
  assert.match(migration, /revoke all on table public\.rate_limit_buckets from public, anon, authenticated/i);
  assert.match(migration, /grant all on table public\.rate_limit_buckets to service_role/i);
  assert.match(migration, /create or replace function public\.consume_rate_limit/i);
  assert.match(migration, /security definer/i);
  assert.match(migration, /on conflict\s*\(bucket_hash\)\s*do update/i);
  assert.match(migration, /p_limit\s*<\s*1|p_limit\s+not between\s+1\s+and/i);
  assert.match(migration, /p_window_seconds\s*<\s*1|p_window_seconds\s+not between\s+1\s+and/i);
  assert.match(migration, /revoke all on function public\.consume_rate_limit/i);
  assert.match(migration, /grant execute on function public\.consume_rate_limit/i);
});

test("adds atomic beta invitations, GitHub profiles, and append-only membership audit", async () => {
  const migration = await readFile(
    new URL("../supabase/migrations/20260815000000_add_beta_membership.sql", import.meta.url),
    "utf8",
  );

  for (const table of ["beta_invitations", "beta_profiles", "beta_membership_events"]) {
    assert.match(migration, new RegExp(`create table if not exists public\\.${table}`, "i"));
  }
  assert.match(migration, /token_hash bytea not null unique/i);
  assert.doesNotMatch(migration, /plaintext|access_token|refresh_token|oauth_token/i);
  assert.match(migration, /revoked_at timestamptz/i);
  assert.match(migration, /primary key \(user_id\)/i);
  assert.match(migration, /unique \(provider, provider_id\)/i);
  assert.match(migration, /invitation_id uuid not null unique/i);
  assert.match(migration, /status text not null.*active.*suspended.*revoked/is);
  assert.match(migration, /create trigger prevent_beta_membership_event_changes/i);
  assert.match(migration, /create or replace function public\.create_beta_invitation/i);
  assert.match(migration, /create or replace function public\.redeem_beta_invitation/i);
  assert.match(migration, /for update/i);
  assert.match(migration, /invitation_created/i);
  assert.match(migration, /invitation_redeemed/i);
  assert.match(migration, /invitation_rejected/i);
  assert.match(migration, /security definer/ig);
  assert.match(migration, /set search_path = ''/i);
  assert.match(migration, /decode\(p_token_hash_hex, 'hex'\)/i);
  assert.match(migration, /p_expires_at > clock_timestamp\(\)/i);
  assert.match(migration, /interval '7 days'/i);
  assert.match(migration, /enable row level security/ig);
  assert.match(migration, /revoke all on table public\.beta_invitations from public, anon, authenticated/i);
  assert.match(migration, /revoke all on table public\.beta_profiles from public, anon, authenticated/i);
  assert.match(migration, /revoke all on table public\.beta_membership_events from public, anon, authenticated/i);
  assert.match(
    migration,
    /grant select, insert on table public\.beta_membership_events to service_role/i,
  );
  assert.doesNotMatch(migration, /grant all on table public\.beta_membership_events to service_role/i);
  assert.match(migration, /revoke all on function public\.create_beta_invitation/i);
  assert.match(migration, /revoke all on function public\.redeem_beta_invitation/i);
  assert.match(migration, /grant execute on function public\.create_beta_invitation.*service_role/is);
  assert.match(migration, /grant execute on function public\.redeem_beta_invitation.*service_role/is);
  assert.match(migration, /consumed_at is not null.*beta_profiles/is);
  assert.match(
    migration,
    /invitation_id = invitation\.id\s+and status = 'active'/i,
  );
  assert.doesNotMatch(migration, /status <> 'revoked'/i);
  assert.match(
    migration,
    /insert into public\.beta_profiles[\s\S]*on conflict do nothing\s+returning \* into profile;\s+if found then\s+update public\.beta_invitations/i,
  );
  assert.doesNotMatch(
    migration,
    /select \*\s+into profile\s+from public\.beta_profiles\s+where user_id = p_user_id\s+or/i,
  );
});

test("adds durable report provenance and resource-bound OAuth access tokens", async () => {
  const migration = await readFile(
    new URL("../supabase/migrations/20260815020000_add_remote_mcp.sql", import.meta.url),
    "utf8",
  );

  assert.match(migration, /alter column reporter_email drop not null/i);
  assert.match(migration, /add column if not exists reporter_user_id uuid/i);
  assert.match(migration, /add column if not exists reporter_provider text/i);
  assert.match(migration, /add column if not exists reporter_provider_id text/i);
  assert.match(migration, /reporter_provider = 'github'/i);
  assert.match(migration, /create index.*reports_reporter_user_id/i);
  assert.doesNotMatch(migration, /reporter_user_id.*references auth\.users/is);
  assert.match(migration, /create or replace function public\.project_builder_access_token_hook/i);
  assert.match(migration, /claims->>'client_id'/i);
  assert.match(
    migration,
    /https:\/\/bbivrybsyxpmkstomccd\.supabase\.co\/functions\/v1\/project-builder-mcp/i,
  );
  assert.match(migration, /grant execute.*supabase_auth_admin/is);
  assert.match(migration, /revoke all.*public, anon, authenticated/is);
});

test("adds private report attachments with hashed upload capabilities", async () => {
  const migration = await readFile(
    new URL("../supabase/migrations/20260815040000_add_report_attachments.sql", import.meta.url),
    "utf8",
  );

  assert.match(migration, /insert into storage\.buckets/i);
  assert.match(migration, /'report-attachments'/i);
  assert.match(migration, /false.*52428800/is);
  assert.match(migration, /image\/png.*image\/jpeg.*video\/mp4.*video\/webm/is);
  assert.match(migration, /create table if not exists public\.report_upload_sessions/i);
  assert.match(migration, /token_hash bytea not null unique/i);
  assert.match(migration, /create table if not exists public\.report_attachments/i);
  assert.match(migration, /status text not null.*pending.*ready.*failed/is);
  assert.match(migration, /create or replace function public\.create_report_upload_session/i);
  assert.match(migration, /create or replace function public\.prepare_report_attachment/i);
  assert.match(migration, /create or replace function public\.complete_report_attachment/i);
  assert.match(migration, /create or replace function public\.fail_report_attachment/i);
  assert.match(migration, /for update/ig);
  assert.match(migration, /count\(\*\).*< 5/is);
  assert.match(migration, /enable row level security/ig);
  assert.match(migration, /revoke all on table public\.report_upload_sessions from public, anon, authenticated/i);
  assert.match(migration, /revoke all on table public\.report_attachments from public, anon, authenticated/i);
  assert.doesNotMatch(migration, /create policy/i);
});
