create table if not exists public.reports (
  id uuid primary key default gen_random_uuid(),
  public_number bigint generated by default as identity,
  title text not null,
  description text not null,
  expected_behavior text not null,
  reproduction_steps text[] not null,
  severity text not null check (severity in ('Low', 'Medium', 'High')),
  type text not null check (type in ('Bug', 'Improvement')),
  status text not null default 'Pending' check (status in ('Pending', 'Validating', 'In construction', 'Resolved', 'Discarded')),
  platform text not null,
  app_version text not null,
  reporter_display_name text not null,
  reporter_email text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (public_number)
);

alter table public.reports enable row level security;

revoke all on table public.reports from anon, authenticated;
grant all on table public.reports to service_role;
grant usage, select on sequence public.reports_public_number_seq to service_role;
